name: Deploy Frontend to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_LEVIATHAN }}
          password: ${{ secrets.DOCKER_PASSWORD_LEVIATHAN }}
          
      - name: Verificar contenido del directorio
        run: |
          ls -la
          echo "Contenido de digitalocean/"
          ls -la digitalocean  
      - name: Build Docker image Digital Ocean
        run: |
          docker build -f digitalocean/Dockerfile -t ${{ secrets.DOCKER_USER_LEVIATHAN }}/digitalocean:latest digitalocean/

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USER_LEVIATHAN }}/digitalocean:latest

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" | base64 -d > EC2.pem
          chmod 600 EC2.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i EC2.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker stop frontend-app || true
            docker rm frontend-app || true
            docker pull ${{ secrets.DOCKER_USER_LEVIATHAN }}/frontend-app:latest
            docker run -d --name frontend-app -p 80:80 ${{ secrets.DOCKER_USER_LEVIATHAN }}/frontend-app:latest
          EOF
